### ISSUE TITLE
LockActivity: Failed to authenticate the user

### ISSUE THREAD

**Issue by anuragjksamanta92** [auth0-samples/auth0-android-sample#91]
### **Implementing Login/Sign Up using Lock Widget**
Getting this error in Logcat:
2020-10-09 20:45:25.928 3473-4954/com.auth0.authoimplementation E/LockActivity: Failed to authenticate the user: An error occurred when trying to authenticate with the server.
    **com.auth0.android.authentication.AuthenticationException: An error occurred when trying to authenticate with the server.**
        at com.auth0.android.request.internal.AuthenticationErrorBuilder.from(AuthenticationErrorBuilder.java:29)
        at com.auth0.android.request.internal.AuthenticationErrorBuilder.from(AuthenticationErrorBuilder.java:12)
        at com.auth0.android.request.internal.BaseRequest.parseUnsuccessfulResponse(BaseRequest.java:139)
        at com.auth0.android.request.internal.SimpleRequest.onResponse(SimpleRequest.java:71)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by icsd** [comment]
Same issue here
